-- create_products.sql
CREATE TABLE IF NOT EXISTS `products` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `parent_category` VARCHAR(255),
  `child_category` VARCHAR(255),
  `sku` VARCHAR(128) UNIQUE,
  `title` TEXT,
  `tags` TEXT,
  `discount` DECIMAL(8,2),
  `list_price` DECIMAL(10,2),
  `star_rating` DECIMAL(3,2),
  `product_description` TEXT,
  `feature1` VARCHAR(255),
  `feature2` VARCHAR(255),
  `feature3` VARCHAR(255),
  `feature4` VARCHAR(255),
  `feature5` VARCHAR(255),
  `feature6` VARCHAR(255),
  `feature7` VARCHAR(255),
  `feature8` VARCHAR(255),
  `brand` VARCHAR(255),
  `main_img` TEXT,
  `img1` TEXT,
  `img2` TEXT,
  `img3` TEXT,
  `img4` TEXT,
  `meta_title` TEXT,
  `meta_description` TEXT,
  `schema_description` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
